name: Make SDK
run-name: Make SDK ${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Platform Tools Version"
        required: true
        default: "36.0.0"
      tag:
        description: "Android Source Tag"
        required: true
        default: "android-16.0.0_r3"

permissions:
  contents: write
  actions: write

jobs:
  build:
    name: Build SDK
    strategy:
      fail-fast: false
      matrix:
        include:
          - target_arch: aarch64
            target_triple: aarch64-linux-musl
          - target_arch: aarch64_be
            target_triple: aarch64_be-linux-musl
          - target_arch: armel
            target_triple: arm-linux-musleabi
          - target_arch: armhf
            target_triple: arm-linux-musleabihf
          - target_arch: armel
            target_triple: armeb-linux-musleabi
          - target_arch: armhf
            target_triple: armeb-linux-musleabihf
          - target_arch: loongarch64
            target_triple: loongarch64-linux-musl
          - target_arch: powerpc64le
            target_triple: powerpc64le-linux-musl
          - target_arch: riscv32
            target_triple: riscv32-linux-musl
          - target_arch: riscv64
            target_triple: riscv64-linux-musl
          - target_arch: s390x
            target_triple: s390x-linux-musl
          - target_arch: x86
            target_triple: x86-linux-musl
          - target_arch: x86_64
            target_triple: x86_64-linux-musl
    uses: ./.github/workflows/main.yml
    with:
      version: ${{ inputs.version }}
      tag: ${{ inputs.tag }}
      target_arch: ${{ matrix.target_arch }}
      target_triple: ${{ matrix.target_triple }}

  make:
    needs: build
    name: Make SDK for ${{ matrix.target_arch }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target_arch: armel
            target_triple: arm-linux-musleabi
          - target_arch: armhf
            target_triple: arm-linux-musleabihf
          - target_arch: armel
            target_triple: armeb-linux-musleabi
          - target_arch: armhf
            target_triple: armeb-linux-musleabihf
          - target_arch: aarch64
            target_triple: aarch64-linux-musl
          - target_arch: aarch64_be
            target_triple: aarch64_be-linux-musl
          - target_arch: loongarch64
            target_triple: loongarch64-linux-musl
          - target_arch: powerpc64le
            target_triple: powerpc64le-linux-musl
          - target_arch: riscv32
            target_triple: riscv32-linux-musl
          - target_arch: riscv64
            target_triple: riscv64-linux-musl
          - target_arch: s390x
            target_triple: s390x-linux-musl
          - target_arch: x86
            target_triple: x86-linux-musl
          - target_arch: x86_64
            target_triple: x86_64-linux-musl
    runs-on: ubuntu-24.04
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v5
      with:
        name: "build-${{ matrix.target_triple }}"

    - name: Delete Artifact
      uses: geekyeggo/delete-artifact@v5.1.0
      with:
        name: "build-${{ matrix.target_triple }}"

    - name: Setup Host Android SDK
      run: |
        export BUILD_TOOLS_VERSION="36.1.0"
        echo BUILD_TOOLS_VERSION=${BUILD_TOOLS_VERSION} >> $GITHUB_ENV
        mkdir android-sdk
        cd android-sdk
        curl -LkSs -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-13114758_latest.zip
        unzip -q commandlinetools.zip
        rm commandlinetools.zip
        yes | cmdline-tools/bin/sdkmanager --sdk_root=. --licenses
        cmdline-tools/bin/sdkmanager --sdk_root=. "build-tools;$BUILD_TOOLS_VERSION" "platform-tools"

    - name: Make Android SDK
      run: |
        HOST_SDK="${PWD}/android-sdk"
        BUILT_SDK="${PWD}/build-${{ matrix.target_triple }}"

        find "${HOST_SDK}/build-tools/$BUILD_TOOLS_VERSION" -type f | while IFS= read -r file; do
            bname="$(basename "${file}")"
            if [ -f "${BUILT_SDK}/${bname}" ] && file "${file}" | grep -q 'ELF'; then
                echo "Replacing ${bname}"
                cp "${BUILT_SDK}/${bname}" "${file}"
            fi
        done

        find "${HOST_SDK}/platform-tools" -type f | while IFS= read -r file; do
            bname="$(basename "${file}")"
            if [ -f "${BUILT_SDK}/${bname}" ] && file "${file}" | grep -q 'ELF'; then
                echo "Replacing ${bname}"
                cp "${BUILT_SDK}/${bname}" "${file}"
            fi
        done

        rm -rf ${HOST_SDK}/build-tools/$BUILD_TOOLS_VERSION/lib64
        rm -rf ${HOST_SDK}/platform-tools/lib64
        rm -rf ${HOST_SDK}/build-tools/$BUILD_TOOLS_VERSION/*-ld ${HOST_SDK}/build-tools/$BUILD_TOOLS_VERSION/lld* ${HOST_SDK}/build-tools/$BUILD_TOOLS_VERSION/llvm-rs-cc ${HOST_SDK}/build-tools/$BUILD_TOOLS_VERSION/bcc_compat ${HOST_SDK}/build-tools/$BUILD_TOOLS_VERSION/renderscript
        sed -i -e '1s|^#!.*bash|#!/bin/sh|' \
               -e 's/^declare -a javaOpts=()/javaOpts=""/' \
               -e 's/javaOpts+=("-\${opt}")/javaOpts="\$javaOpts -\${opt}"/' \
               -e 's/javaOpts+=("\${defaultMx}")/javaOpts="\$javaOpts \${defaultMx}"/' \
               -e 's|"\${javaOpts\[@\]}"|$javaOpts|' ${HOST_SDK}/build-tools/$BUILD_TOOLS_VERSION/d8
        sed -i '1s|^#!.*bash|#!/bin/sh|' ${HOST_SDK}/build-tools/$BUILD_TOOLS_VERSION/apksigner

    - name: Archive
      run: tar -cf - android-sdk | xz -T0 -9e --lzma2=dict=256MiB > android-sdk-${{matrix.target_triple}}.tar.xz

    - name: Upload Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: android-sdk-${{matrix.target_triple}}
        path: android-sdk-${{matrix.target_triple}}.tar.xz

  release:
    needs: make
    runs-on: ubuntu-24.04
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v5
      with:
        merge-multiple: true

    - name: Delete Artifacts
      uses: geekyeggo/delete-artifact@v5.1.0
      with:
        name: android-sdk-*

    - name: Release
      uses: ncipollo/release-action@v1.20.0
      with:
        tag: "${{inputs.version}}"
        artifacts: "android-sdk-*"
        allowUpdates: true
        replacesArtifacts: true
        body: ''
        
